# Définition des variables
variables:
  dockerRegistryServiceConnection: 'ConnectDockerHub'
  imageRepository: 'k8b8nm'
  containerRegistry: 'nemesys34'
  repository: 'nemesys34/k8b8nm'
  kubernetesServiceEndpoint: 'connectK8SNM'
  clusterName: 'K8B8NM'

# Déclencheur
trigger:
- master

# Définition du pool d'agents
pool:
  vmImage: ubuntu-latest

# Étapes du pipeline
steps:

- task: Docker@2
  inputs:
    containerRegistry: $(containerRegistry)
    repository: $(repository)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildNumber)'
    arguments: '--build-arg IMAGE_REPOSITORY=$(imageRepository)'
  displayName: 'Construction et envoi de l\'image Docker'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: $(kubernetesServiceEndpoint)
    namespace: 'qal'
    manifests: '$(System.DefaultWorkingDirectory)/azure-pipelines-1.yml'
    command: 'apply'
    arguments: '--namespace=qal'
  displayName: 'Déploiement sur le cluster Kubernetes'
  condition: succeeded('Docker@2')
