apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redisvol
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisclaim
spec:
  accessModes:
    - ReadWriteOnce
  ressources:
    request:
      storage: 1Gi
  storageClassName: redisvol